platform :ios, '10.0'

inhibit_all_warnings!

target 'App' do
    # react-native-rxinput #不需要导入，因为都是js代码
      pod 'React', :path => '../node_modules/react-native/'
      pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon'
#      pod 'React-Fabric', :path => '../node_modules/react-native/ReactCommon'

  	# 如果你的RN版本 >= 0.42.0，则加入下面这行
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

#  	 # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  	pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

 pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

	post_install do |installer|
	    installer.pods_project.build_configurations.each do |config|
	      config.build_settings['SYMROOT'] = '${SRCROOT}/../build'
	    end
  	end
end
