platform :ios, '9.0'

inhibit_all_warnings!

target 'App' do
    # react-native-rxinput #不需要导入，因为都是js代码
    #  pod 'React', :path => '../node_modules/react-native/'
    #  pod 'React-Core', :path => '../node_modules/react-native/React'
    #  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
    #  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
    #  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    #  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    #  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    #  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    #  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    #  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    #  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    #  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    #  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
    #  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
    #
    #  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    #  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    #  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    #  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    #  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    #
    #  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    #  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    #  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


    # React-Native
  	pod 'React', :path => '../node_modules/react-native', :subspecs => [
    	'Core',
    	'CxxBridge', # 如果RN版本 >= 0.45则加入此行
    	'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
      'RCTText',
      'RCTImage',
      'RCTNetwork',
      'RCTSettings',
      'RCTVibration',
      'RCTAnimation',
      'RCTActionSheet',
      'RCTGeolocation',
    	'RCTWebSocket', # 这个模块是用于调试功能的

    	# 在这里继续添加你所需要的RN模块
	    'ART',
      'RCTBlob',
      'RCTCameraRoll',
      'RCTLinkingIOS',
      'RCTGeolocation',
      'RCTPushNotification'
  	]
    
  	# 如果你的RN版本 >= 0.42.0，则加入下面这行
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  	 # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  	pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

	post_install do |installer|
	    installer.pods_project.build_configurations.each do |config|
	      config.build_settings['SYMROOT'] = '${SRCROOT}/../build'
	    end
  	end
end
